docops/coreapp/urls.py
from django.urls import path
from . import views

app_name = 'coreapp'

urlpatterns =[
    path('',views.home,name='home'),
    path('doctor/',views.doctor,name='doctor'),
    
]

docops/docops/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('coreapp.urls')),
    path('user/',include('user.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

docops/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns =[
    path('login/',views.Login,name='login'),
    path('logout/',views.Logout,name='logout'),
    path('signup/',views.Signup,name='signup'),
]

docops/coreapp/models.py
from django.db import models
from django.conf import settings
# Create your models here.

# class Patient(models.Model):
#     user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE) 
#     def __str__(self):
#         return self.user

    
# class Schedule(models.Model):
    
#     def __str__(self):
#         return self.title
    
# class Booking(models.Model):
    
#     def __str__(self):
#         return self.title
    
# class Hospital(models.Model):
    
#     def __str__(self):
#         return self.title

# class Doctor(models.Model):
    
#     def __str__(self):
#         return self.title    

docops/coreapp/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home.html')

def file(request):
    if request.method == 'POST':
        print(request.FILE)

def doctor(request):
    return render(request,'doctor.html',{})

docops/coreapp/templates/doctor.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Doctor{% endblock %}
{% block content %}
    <h1>Doctor</h1> 
    <a href="{% url 'coreapp:home' %}" >home</a>
   
{% endblock %}

docops/coreapp/templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Home{% endblock %}
{% block content %}
<h1>Home</h1> 
{% if user.is_authenticated %}
    {{user.email}}
    <a href="{% url 'user:logout' %}">Logout</a>
{% else %}
    <a href="{% url 'user:login' %}">Login</a>

{% endif %}

    <a href="{% url 'coreapp:doctor' %}" >doctor</a>
{% endblock %}

docops/coreapp/templates/j.html
<!DOCTYPE html>
<html>
  <head>
    <title>Simple registration form</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <style>
      html, body {
      display: flex;
      justify-content: center;
      height: 100%;
      }
      body, div, h1, form, input, p { 
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 16px;
      color: #666;
      }
      h1 {
      padding: 10px 0;
      font-size: 32px;
      font-weight: 300;
      text-align: center;
      }
      p {
      font-size: 12px;
      }
      hr {
      color: #a9a9a9;
      opacity: 0.3;
      }
      .main-block {
      max-width: 340px; 
      min-height: 460px; 
      padding: 10px 0;
      margin: auto;
      border-radius: 5px; 
      border: solid 1px #ccc;
      box-shadow: 1px 2px 5px rgba(0,0,0,.31); 
      background: #ebebeb; 
      }
      form {
      margin: 0 30px;
      }
      .account-type, .gender {
      margin: 15px 0;
      }
      input[type=radio] {
      display: none;
      }
      label#icon {
      margin: 0;
      border-radius: 5px 0 0 5px;
      }
      label.radio {
      position: relative;
      display: inline-block;
      padding-top: 4px;
      margin-right: 20px;
      text-indent: 30px;
      overflow: visible;
      cursor: pointer;
      }
      label.radio:before {
      content: "";
      position: absolute;
      top: 2px;
      left: 0;
      width: 20px;
      height: 20px;
      border-radius: 50%;
      background: #1c87c9;
      }
      label.radio:after {
      content: "";
      position: absolute;
      width: 9px;
      height: 4px;
      top: 8px;
      left: 4px;
      border: 3px solid #fff;
      border-top: none;
      border-right: none;
      transform: rotate(-45deg);
      opacity: 0;
      }
      input[type=radio]:checked + label:after {
      opacity: 1;
      }
      input[type=text], input[type=password] {
      width: calc(100% - 57px);
      height: 36px;
      margin: 13px 0 0 -5px;
      padding-left: 10px; 
      border-radius: 0 5px 5px 0;
      border: solid 1px #cbc9c9; 
      box-shadow: 1px 2px 5px rgba(0,0,0,.09); 
      background: #fff; 
      }
      input[type=password] {
      margin-bottom: 15px;
      }
      #icon {
      display: inline-block;
      padding: 9.3px 15px;
      box-shadow: 1px 2px 5px rgba(0,0,0,.09); 
      background: #1c87c9;
      color: #fff;
      text-align: center;
      }
      .btn-block {
      margin-top: 10px;
      text-align: center;
      }
      button {
      width: 100%;
      padding: 10px 0;
      margin: 10px auto;
      border-radius: 5px; 
      border: none;
      background: #1c87c9; 
      font-size: 14px;
      font-weight: 600;
      color: #fff;
      }
      button:hover {
      background: #26a9e0;
      }
    </style>
  </head>
  <body>
    
  </body>
</html>

docops/coreapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    
    {% endblock %}
</body>
</html>