docops/docops/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('coreapp.urls')),
    path('user/',include('user.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

docops/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns =[
    path('login/',views.Login,name='login'),
    path('logout/',views.Logout,name='logout'),
    path('signup/',views.Signup,name='signup'),
]

docops/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.
#-------------------USER-------------------------
#--------usermanager----------
class UserAccountManager(BaseUserManager):
    def create_superuser(self, email, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)
        other_fields.setdefault('is_admin', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')
        if other_fields.get('is_admin') is not True:
            raise ValueError(
                'Superuser must be assigned to is_admin=True.')

        return self.create_user(email, password, **other_fields)

    def create_user(self, email, password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email,
                            **other_fields)
        user.set_password(password)
        user.save()
        return user
    
#--------user----------
class User(AbstractBaseUser,PermissionsMixin):
    #adding custom field "role" in default User model
    class Role(models.TextChoices):
        ADMIN = "ADMIN",'Admin'
        DOCTOR = "DOCTOR",'Doctor'
        PATIENT = "PATIENT",'Patient'

    base_role = Role.ADMIN
    
    role = models.CharField(max_length=50,choices=Role.choices,default=Role.ADMIN)
    email = models.EmailField(_('email address'), unique=True)
    is_active = models.BooleanField(default = True)
    is_admin = models.BooleanField(default = False)
    is_staff = models.BooleanField(default = False)
    is_superuser = models.BooleanField(default = False)
      
    # special permission which define that
    # the new user is doctor or patient 
    is_doctor = models.BooleanField(default = False)
    is_patient = models.BooleanField(default = False)
    
      
    USERNAME_FIELD = "email"
      
    # defining the manager for the UserAccount model
    objects = UserAccountManager()
      
    def __str__(self):
        return str(self.email)
      
    def has_perm(self , perm, obj = None):
        return self.is_admin
      
    def has_module_perms(self , app_label):
        return True
    def save(self,*args,**kwargs):
        if not self.pk:
            self.role = self.base_role
            return super().save(*args,**kwargs)
        
#------------Patient------------------------------        
class PatientManager(models.Manager):

     # def create_user(self , email , password = None):
     #    if not email or len(email) <= 0 : 
     #        raise  ValueError("Email field is required !")
     #    if not password :
     #        raise ValueError("Password is must !")
     #    email  = email.lower()
     #    user = self.model(
     #        email = email
     #    )
     #    user.set_password(password)
     #    user.save(using = self._db)
     #    return user    

     def get_queryset(self,*args,**kwargs):
          results = super().get_queryset(*args,**kwargs)
          return results.filter(role=User.Role.PATIENT)
#patient proxy class  for setting baserole    
class Patient(User):
    base_role = User.Role.PATIENT

    patient = PatientManager()

    class Meta:
            proxy = True

#Automatic creation of UserProfile during UserCreation
@receiver(post_save,sender=Patient)
def create_user_profile(sender,instance,created,**kwargs):
     if created and instance.role == "PATIENT":
          PatientProfile.objects.create(user=instance)

#userprofile to created user
class PatientProfile(models.Model):
     user = models.OneToOneField(User,on_delete=models.CASCADE)
     patient_id = models.IntegerField(null=True,blank=True)
     first_name = models.CharField(max_length=150, blank=True)
     last_name = models.CharField(max_length=150, blank=True)
     address = models.CharField(max_length=50,null=True,blank=True)

     def __str__(self):
          return self.user.username
#---------------Doctor---------------------------------------- 
class DoctorManager(models.Manager):
     # def create_user(self , email , password = None):
     #    if not email or len(email) <= 0 : 
     #        raise  ValueError("Email field is required !")
     #    if not password :
     #        raise ValueError("Password is must !")
     #    email  = email.lower()
     #    user = self.model(
     #        email = email
     #    )
     #    user.set_password(password)
     #    user.save(using = self._db)
     #    return user    
     
     def get_queryset(self,*args,**kwargs):
          results = super().get_queryset(*args,**kwargs)
          return results.filter(role=User.Role.DOCTOR)
#doctor role class     
class Doctor(User):
    base_role = User.Role.DOCTOR

    doctor = DoctorManager()

    class Meta:
            proxy = True

#Automatic creation of UserProfile during UserCreation
@receiver(post_save,sender=Doctor)
def create_user_profile(sender,instance,created,**kwargs):
     if created and instance.role == "DOCTOR":
          DoctorProfile.objects.create(user=instance)

#userprofile to created user
class DoctorProfile(models.Model):
     user = models.OneToOneField(User,on_delete=models.CASCADE)
     doctor_id = models.IntegerField(null=True,blank=True)
     first_name = models.CharField(max_length=150, blank=True)
     last_name = models.CharField(max_length=150, blank=True)

     def __str__(self):
          return self.user.username

docops/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import get_user_model
User = get_user_model()


class SignupForm(UserCreationForm):
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(
            attrs={
                'class': 'input',
                'placeholder': 'user@example.com'
            })
    )
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'password',
                'placeholder': 'password'
            })
    )
    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(
            attrs={
                "class": "password",
                "placeholder": "confirm password"
            })
    )

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(
            attrs={
                'class': 'input',
                'placeholder': 'user@example.com'
            })
    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'password',
                'placeholder': 'password'
            })
    )

    class Meta:
        model = User
        fields = "__all__"

docops/user/views.py
from django.shortcuts import render,redirect,reverse
from . forms import SignupForm,LoginForm
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login, logout

User = get_user_model()

def Signup(request):
    form = SignupForm()
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            return render(request, 'signup.html', {
                'form': form,
                'error': True,
            })
    return render(request,'signup.html',{
        'form': form,
        'error': False
    })

def Login(request):
    if request.user.is_authenticated:
        return redirect(reverse('coreapp:home'))

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username =username, password = password)
 
        if user is not None:
            login(request,user)
            return redirect(reverse('coreapp:home'))
        else:
            print("login error")
            form = LoginForm()
            return render(request,'login.html',{'form':form})
     
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form':form})

def Logout(request):
    logout(request)
    return redirect(reverse('coreapp:home'))

docops/user/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    {% block css %}{% endblock %}
</head>

<body>
    {% block content %}

    {% endblock %}
</body>

</html>

docops/user/templates/login.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Login{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'user/style.css' %}">
<script src="{% static 'user/script.js' %}"></script>
<link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

{% endblock %}
{% block content %}
<section class="container forms">
    <div class="form login">
        <div class="form-content">
            <header>Login</header>
            <form action="#" method="post">
                {% csrf_token %}
                {% if error == True %}
                <span style="color: red">
                    {{form.errors}}
                </span>
                {% endif %}

                <div class="field input-field">
                    {{form.username}}
                </div>

                <div class="field input-field">
                    {{form.password}}
                    <i class='bx bx-hide eye-icon'></i>
                </div>

                <div class="form-link">
                    <a href="#" class="forgot-pass">Forgot password?</a>
                </div>

                <div class="field button-field">
                    <input type="submit" class="btn" value="Login">
                </div>
            </form>

            <div class="form-link">
                <span>Don't have an account? <a href="{% url 'user:signup' %}" class="link signup-link">Signup</a></span>
            </div>
        </div>

        
    </div>


</section>
{% endblock %}

docops/user/templates/logout.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Logout{% endblock %}
{% block content %}
    Logout
{% endblock %}

docops/user/templates/signup.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Signup{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'user/style.css' %}">
<script src="{% static 'user/script.js' %}"></script>
<script src="https://kit.fontawesome.com/45978a437e.js" crossorigin="anonymous"></script>

{% endblock %}
{% block content %}
<section class="container forms">
    <div class="form login">
        <div class="form-content">
            <header>Signup</header>
            <form action="" method="post">{% csrf_token %}
                {% if error == True %}
                <span style="color: red">{{form.errors}}</span>
                {% endif %}
                <div class="field input-field">

                    {{form.email}}

                </div>

                <div class="field input-field">

                    {{form.password1}}

                </div>

                <div class="field input-field">
                    {{form.password2}}
                    <i class='bx bx-hide eye-icon'></i>
                </div>
                <div class="field button-field">
                    <input type="submit" value="Signup" class="btn">
                </div>
            </form>

            <div class="form-link">
                <span>Already have an account? <a href="{% url 'user:login' %}" class="link login-link">Login</a></span>
            </div>
        </div>



    </div>
</section>

{% endblock %}